### ISSUE TITLE
复现时候的问题

### ISSUE THREAD

**Issue by MingtanSun** [OpenMeow/NTIRE23_LFSR_DistgEPIT#2]
在跑lfsr.py的时候，有报错，内容如下
Traceback (most recent call last):
  File "C:\Users\86137\PycharmProjects\pythonProject3\lfsr.py", line 1005, in <module>
    LFSR(config)()
  File "C:\Users\86137\PycharmProjects\pythonProject3\lfsr.py", line 450, in __init__
    self.Model = self.build_model()
  File "C:\Users\86137\PycharmProjects\pythonProject3\lfsr.py", line 519, in build_model
    raise NotImplementedError(cfg.model)
NotImplementedError: None

**Comment by atranitell** [comment]
how does you run this code?

**Comment by MingtanSun** [comment]
作者的Training & Test部分使用了linux或unix命令，在windows中可以在terminal里运行python lfsr.py train，前提是你已经准备好了训练测试数据
当我运行这个命令后，程序报错了

**Comment by atranitell** [comment]
Referring to ./lfsr.sh script to run this model

**Comment by MingtanSun** [comment]
谢谢：）
